#ifndef SCEV_H
#define SCEV_H

#include "IR/Module.h"
#include "Optimize/Analysis/LoopInfo.h"
#include <map>
#include <vector>

namespace sysy {

struct SE {
    enum Kind { Const, Unknown, Add, Mul, AddRec };
    Kind kind;
protected:
    SE(Kind k) : kind(k) {}
public:
    virtual ~SE() = default;
};

struct SEConst : SE {
    int64_t val;
    explicit SEConst(int64_t v) : SE(Const), val(v) {}
    static bool classof(const SE* s) { return s->kind == Const; }
};

struct SEUnknown : SE {
    Value* v;
    explicit SEUnknown(Value* v) : SE(Unknown), v(v) {}
    static bool classof(const SE* s) { return s->kind == Unknown; }
};

struct SEAdd : SE {
    std::vector<SE*> ops;
    explicit SEAdd(std::vector<SE*> o) : SE(Add), ops(std::move(o)) {}
    static bool classof(const SE* s) { return s->kind == Add; }
};

// base * factor  (factor is a non-zero constant)
struct SEMul : SE {
    SE* base;
    int64_t factor;
    SEMul(SE* b, int64_t f) : SE(Mul), base(b), factor(f) {}
    static bool classof(const SE* s) { return s->kind == Mul; }
};

// n = start + step*n { start, +, step }L
struct SEAddRec : SE {
    SE* start;
    int64_t step;
    Loop* loop;
    SEAddRec(SE* s, int64_t st, Loop* l) : SE(AddRec), start(s), step(st), loop(l) {}
    static bool classof(const SE* s) { return s->kind == AddRec; }
};

class SCEV {
public:
    SCEV(Function* /*f*/, LoopInfo& li) : LI(li) {}
    ~SCEV() { for (auto s : Owned) delete s; }

    SE* get(Value* v);
    SE* add(SE* a, SE* b);
    SE* sub(SE* a, SE* b);
    SE* mul(SE* a, int64_t factor);
    
    // Range Query
    bool pos(SE* s); // s > 0
    bool nneg(SE* s); // s >= 0 (non-negative)
    bool distinct(SE* a, SE* b); // address(a) != address(b)

private:
    LoopInfo& LI;
    std::map<Value*, SE*> Cache;
    std::vector<SE*> Owned;

    // Register the bare pointers generated by new nodes in the Owned, 
    // and unify delete during destructuring to avoid leakage.
    SE* own(SE* s) { Owned.push_back(s); return s; }
    SE* buildPhi(PhiInst* phi);
    SE* buildGEP(GetElementPtrInst* gep);
    SE* neg(SE* s);
    SE* simplAdd(std::vector<SE*>& ops);
};

}
#endif
